name: Build Mod
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '25'
          cache: 'gradle'
      - name: Build with Gradle
        run: gradle build
      - name: Upload Mod JAR
        uses: actions/upload-artifact@v4
        with:
          name: Fabric-Mod-JAR
          path: build/libs/*.jar
